services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    entrypoint: sh -c "yarn install && yarn serve"
    ports:
      - 3000:8080
    volumes:
      - ./frontend:/usr/local/src
    environment:
      - NODE_ENV=local
      - VUE_APP_API_BASE_URL=http://localhost:8000/api/v1
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - proxy

  proxy:
    image: nginx:1.19-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/common_proxy.conf:/etc/nginx/conf.d/common_proxy.conf
    ports:
      - 8000:80
    depends_on:
      - catalog
      - products
      - warehouse
      - ratings
      - orders

  products:
    image: ramageek/image:php8.1-laravel
    volumes:
      - ./products:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:7t3iJGYKu1jqjeEQixGEL8mXwCr6XgVRmd6ryRII3Jo=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=products
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    depends_on:
      - mysql

  ratings:
    image: ramageek/image:php8.1-laravel
    volumes:
      - ./ratings:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:7t3iJGYKu1jqjeEQixGEL8mXwCr6XgVRmd6ryRII3Jo=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=ratings
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    depends_on:
      - mysql

  ratings-consumer:
    image: ramageek/image:php8.1-laravel
    command: ["php", "/var/www/html/artisan", "short-schedule:run", "--lifetime=60"]
    stop_signal: SIGTERM
    restart: unless-stopped
    volumes:
      - ./ratings:/var/www/html
    environment:
      - APP_NAME=RatingsConsumer
      - APP_ENV=local
      - APP_KEY=base64:7t3iJGYKu1jqjeEQixGEL8mXwCr6XgVRmd6ryRII3Jo=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=ratings
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    depends_on:
      - mysql
      - redis
      - ratings

  warehouse:
    image: ramageek/image:php8.1-laravel
    volumes:
      - ./warehouse:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:7t3iJGYKu1jqjeEQixGEL8mXwCr6XgVRmd6ryRII3Jo=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=warehouse
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    depends_on:
      - mysql

  warehouse-consumer:
    image: ramageek/image:php8.1-laravel
    command: ["php", "/var/www/html/artisan", "short-schedule:run", "--lifetime=60"]
    stop_signal: SIGTERM
    restart: unless-stopped
    volumes:
      - ./warehouse:/var/www/html
    environment:
      - APP_NAME=WarehouseConsumer
      - APP_ENV=local
      - APP_KEY=base64:7t3iJGYKu1jqjeEQixGEL8mXwCr6XgVRmd6ryRII3Jo=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=warehouse
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    depends_on:
      - mysql
      - redis
      - warehouse

  catalog:
    image: ramageek/image:php8.1-laravel
    volumes:
      - ./catalog:/var/www/html
    environment:
      - SERVICES_PRODUCTS_URL=http://products/api/v1/
      - SERVICES_WAREHOUSE_URL=http://warehouse/api/v1/
      - SERVICES_RATINGS_URL=http://ratings/api/v1/
      - APP_ENV=local
      - APP_KEY=base64:7t3iJGYKu1jqjeEQixGEL8mXwCr6XgVRmd6ryRII3Jo=
      - APP_DEBUG=true
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    depends_on:
      - mysql

  orders:
    image: ramageek/image:php8.1-laravel
    volumes:
      - ./orders:/var/www/html
    environment:
      - SERVICES_WAREHOUSE_URL=http://warehouse/api/v1/
      - APP_ENV=local
      - APP_KEY=base64:7t3iJGYKu1jqjeEQixGEL8mXwCr6XgVRmd6ryRII3Jo=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=orders
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    depends_on:
      - mysql

  orders-consumer:
    image: ramageek/image:php8.1-laravel
    command: ["php", "/var/www/html/artisan", "short-schedule:run", "--lifetime=60"]
    stop_signal: SIGTERM
    restart: unless-stopped
    volumes:
      - ./orders:/var/www/html
    environment:
      - APP_NAME=OrdersConsumer
      - APP_ENV=local
      - APP_KEY=base64:7t3iJGYKu1jqjeEQixGEL8mXwCr6XgVRmd6ryRII3Jo=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=orders
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    depends_on:
      - mysql
      - redis
      - warehouse

  mysql:
    image: mysql:8
    platform: linux/x86_64
    volumes:
      - ./bin/mysql:/docker-entrypoint-initdb.d
      - ./mysqldata:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:6.2.5-alpine
    platform: linux/x86_64
    volumes:
      - ./redisdata:/data
    ports:
      - 63790:6379

  phpmyadmin:
    image: phpmyadmin
    platform: linux/x86_64
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  redis-commander:
    image: rediscommander/redis-commander:latest
    platform: linux/x86_64
    hostname: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 63791:8081
    depends_on:
      - redis

  mysql-test:
    image: mysql:8
    platform: linux/x86_64
    volumes:
      - ./bin/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis-test:
    image: redis:6.2.5-alpine
    platform: linux/x86_64
