version: '2.8'
services:
  products:
    image: $JOB_IMAGE_NAME_DEV
    environment:
      - APP_ENV=testing
      - APP_KEY=base64:7t3iJGYKu1jqjeEQixGEL8mXwCr6XgVRmd6ryRII3Jo=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-test
      - DB_PORT=3306
      - DB_DATABASE=test
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis-test
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    depends_on:
      mysql-test:
        condition: service_healthy
      redis-test:
        condition: service_started

  mysql-test:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:6.0
    restart: unless-stopped
